### ISSUE TITLE
Nerf vandal

### ISSUE THREAD

**Issue by bensegal2034** [bensegal2034/TTT_Custom_Server_V2#10]
The vandal clearly needs to be toned down as its effectivness in spraying someone from close to medium range is far too strong. Combined with its ability to 1 shot headshot, it is the strongest primary available and one of the strongest guns in the game. 

The approach to nerfing the vandal could be done in two different ways.

## Approach 1

Return the vandal's perfect accuracy while moving. However, the first bullet is the only one that is accurate. Any subsequent bullets fired will pick a direction so that they miss all players or entities, and their damage will be set to zero. This will occur until the player stops firing, at which point the gun is placed on a cooldown for some time (~3-4 seconds).

This approach would give the vandal identity as *the* funny Valorant gun, while reducing its effectiveness massively. Picking it would be extremely risky but rewarding if you manage to land the first shot, and force more reliance onto your secondary as your primary will effectively be on cooldown for several seconds after a shot. However, it also could make the gun less fun to use as missing your first shot is extremely punishing. This approach could furthermore become oppressive when the weapon is used by a Traitor, as Traitors generally have the luxury of being able to line up their first shot on an unsuspecting Innocent or Detective.

## Approach 2

Reduce the vandal's inaccuracy, but nerf its bodyshot damage by a substantial amount.

This change would make the vandal far more reasonable to play against, as a spray would take a comparable amount of time to the other weapons that are commonly sprayed such as SMGs and other rifles. Currently, the vandal does 28 damage on a bodyshot, which is best in class by far. This is supposed to be countered by its low accuracy, but shots still manage to find their mark regardless of this.

## Resolution

Both of these approaches should be made in code and playtested, after which a vote should be made on which approach to keep.

**Comment by hage05** [comment]
I think the Vandal's problem goes far beyond the scope of potential nerfs. The way the weapon functions right now does not work with how we intended as we wanted to model it as similar as we could from Valorant. 

For example, with the Vandal you are still able to consistently tap fire the weapon in Valorant, but not with the current Vandal we have. It becomes immediately inaccurate after firing the first shot, instead of taking other shots into account. This is the main problem with the weapon.

I think it would be best to completely rework it. In Valorant you have to tap fire, but in our cases its not really the same case. 

Approach 3:

- Reduce bodyshot damage 
- Add a working ADS function for additional accuracy for long range distances. 
- Allow tap-firing without added inaccuracy unless the player decides to spray.

These changes would more or less make it similar to the Guardian, but that is what the weapon should have been from the start. It should be a tap firing weapon, and if you are forced to spray you just have to hope it hits or be super close. People should be rewarded for hitting their taps and this change will always make it a much more skill based weapon.

**Comment by bensegal2034** [comment]
Resolved by commit bd7af9236caf3d44ed4095236ab636698e506c3f
